# Numpy -> numerical python

# pip install numpy

In [1]:
import numpy as np

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [6]:
array = np.array([1, 2, 3, 4, 5, 6])
array, type(array), array.dtype

(array([1, 2, 3, 4, 5, 6]), numpy.ndarray, dtype('int64'))

In [7]:
array = np.array([1, 2, 3, 4, 5, 6.4])
array, type(array), array.dtype

(array([1. , 2. , 3. , 4. , 5. , 6.4]), numpy.ndarray, dtype('float64'))

In [8]:
array = np.array([1, 2, 3, 4, 5, "hello"])
array, type(array), array.dtype

(array(['1', '2', '3', '4', '5', 'hello'], dtype='<U21'),
 numpy.ndarray,
 dtype('<U21'))

In [13]:
array = np.array([ [1, 2, 3], [4, 5, 6]])
array, array.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [14]:
array = np.array([ [1, 2, 3], [4, 5, 6]])
array, array.reshape(3, 2)

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [15]:
array = np.array(range(10))
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
array = np.arange(10)
array + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
array = np.arange(10)
array ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [19]:
array1 = np.array([20, 30, 40])
array2 = np.array([10, 10, 10])
array1 + array2


array([30, 40, 50])

In [20]:
array1 = np.array([20, 30, 40])
array2 = np.array([10, 10, 10])
array1 - array2

array([10, 20, 30])

In [21]:
array1 = np.array([20, 30, 40])
array2 = np.array([10, 10, 10])
array1 * array2

array([200, 300, 400])

In [22]:
np.random.random()

0.22315658010155304

In [23]:
np.random.random()

0.6222066683941936

In [24]:
np.random.random(5)

array([0.19711394, 0.05338843, 0.26116011, 0.99677115, 0.37106295])

In [25]:
np.random.randint(1, 100, 5)

array([91, 32, 12, 49, 82])

In [33]:
np.random.randint(1, 100, 5)

array([68, 45, 21, 76, 70])

In [35]:
array = np.random.randint(1, 100, 30)
array

array([62, 97, 97, 30, 82, 61, 71, 31, 64, 26, 44, 45, 56, 19, 81, 51, 11,
       86, 76, 98, 88, 72, 52, 22, 24, 73, 22, 44, 70, 41])

In [36]:
array - 50

array([ 12,  47,  47, -20,  32,  11,  21, -19,  14, -24,  -6,  -5,   6,
       -31,  31,   1, -39,  36,  26,  48,  38,  22,   2, -28, -26,  23,
       -28,  -6,  20,  -9])

In [37]:
array + array

array([124, 194, 194,  60, 164, 122, 142,  62, 128,  52,  88,  90, 112,
        38, 162, 102,  22, 172, 152, 196, 176, 144, 104,  44,  48, 146,
        44,  88, 140,  82])

In [38]:
array 

array([62, 97, 97, 30, 82, 61, 71, 31, 64, 26, 44, 45, 56, 19, 81, 51, 11,
       86, 76, 98, 88, 72, 52, 22, 24, 73, 22, 44, 70, 41])

In [39]:
array > 50

array([ True,  True,  True, False,  True,  True,  True, False,  True,
       False, False, False,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True, False, False,  True, False,
       False,  True, False])

In [40]:
array

array([62, 97, 97, 30, 82, 61, 71, 31, 64, 26, 44, 45, 56, 19, 81, 51, 11,
       86, 76, 98, 88, 72, 52, 22, 24, 73, 22, 44, 70, 41])

In [42]:
array[0], array[7]

(np.int64(62), np.int64(31))

In [43]:
array[0:7]

array([62, 97, 97, 30, 82, 61, 71])

In [44]:
array[array > 50]

array([62, 97, 97, 82, 61, 71, 64, 56, 81, 51, 86, 76, 98, 88, 72, 52, 73,
       70])

In [45]:
array[array < 50]

array([30, 31, 26, 44, 45, 19, 11, 22, 24, 22, 44, 41])

In [46]:
array[(array < 50) & (array > 25)]

array([30, 31, 26, 44, 45, 44, 41])

In [47]:
array[(array > 50) | (array < 25)]

array([62, 97, 97, 82, 61, 71, 64, 56, 19, 81, 51, 11, 86, 76, 98, 88, 72,
       52, 22, 24, 73, 22, 70])

In [48]:
(array > 50)

array([ True,  True,  True, False,  True,  True,  True, False,  True,
       False, False, False,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True, False, False,  True, False,
       False,  True, False])