In [1]:
import numpy as np

In [4]:
array1 = np.arange(10, 13)
array1

array([10, 11, 12])

In [8]:
array2 = np.random.randint(1, 100, 3)
array2

array([91, 12, 49])

In [9]:
array1 + array2

array([101,  23,  61])

In [12]:
array = np.arange(1000, 2000, 100)
array

array([1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900])

In [13]:
array.min(), array.max()

(np.int64(1000), np.int64(1900))

In [14]:
array.size

10

In [15]:
array.reshape(5, 2)

array([[1000, 1100],
       [1200, 1300],
       [1400, 1500],
       [1600, 1700],
       [1800, 1900]])

In [16]:
array.reshape(2, 5)

array([[1000, 1100, 1200, 1300, 1400],
       [1500, 1600, 1700, 1800, 1900]])

In [18]:
array_5_2 = array.reshape(2, 5)
array_5_2

array([[1000, 1100, 1200, 1300, 1400],
       [1500, 1600, 1700, 1800, 1900]])

In [19]:
array_5_2[1]

array([1500, 1600, 1700, 1800, 1900])

In [20]:
array_5_2[1][3]

np.int64(1800)

In [21]:
array_5_2[1, 3]

np.int64(1800)

In [23]:
array_5_2[ : , 2: ]

array([[1200, 1300, 1400],
       [1700, 1800, 1900]])

In [26]:
array_5_2 [ array_5_2 % 3 == 0]

array([1200, 1500, 1800])